### ISSUE TITLE
Any alternatives to index in order to know if getting to end?

### ISSUE THREAD

**Issue by adjourn** [caseywebdev/react-list#146]
I cannot find a way to use this component in "true React way", as a reactive component that feeds off the `props` from parent. I find `itemRenderer` very unpredictable and Im wondering if there are any alternatives.

``` js
<ReactList 
    type='uniform' 
    itemRenderer={this._renderItem.bind(this)} 
    items={this.props.items}
    length={this.props.items.length} 
    pageSize={5}  
/>


_renderItem(index, key) {
    // Data is fetched in parent and it's state "isLoading" is true while it's getting data
    if (index + 1 >= this.props.items.length && !this.props.isLoading) { 
        this._makeRequest(index)
    }

    const item = <Item i={index} item={this.props.items[index]} height={100} />

    return <div key={key}>{item}</div>
}

_makeRequest(index) {
    // Calling parent's method to get more data
    this.props.loadMore && this.props.loadMore(index)
}
```
### PROBLEM:

`itemRenderer` is called pretty unpredictably and several times (depends what `pageSize`, `threshold` _etc_ are). React `setState()` is not instant (it's asynchronous), which means that `this.props.isLoading` is not 100% accurate and request triggers several times, sometimes even gets stuck to infinite loop. Please advice.

Im using `isLoading` state on parent because there are some DOM differences if I load more data in.

**Comment by Bamieh** [comment]
just like with any stateless component (the `_renderItem `) in your case, you should not be making requests inside it.

**Comment by unirey** [comment]
@Bamieh 

Im making a request in parent component and all related closed issues recommend similar strategy, _a'la_ check `index` in `renderItem()` and if it's (among) the last `index`(es), make a request.  

No matter what or where I do it, duplicate execution problem just bubbles up. Im not sure how to ensure single execution with async data detching because `itemRenderer` causes unpredictable updates, which could happen before new data arrives or even before `this.prop.isLoading` changes and avoids new requests.

**Comment by unirey** [comment]
@Bamieh 

Im making a request in parent component and all related closed issues recommend similar strategy, _a'la_ check `index` in `renderItem()` and if it's (among) the last `index`(es), make a request. That's what my issue is about.. Is there any other way to know if Im getting to the end of list?

No matter what or where I do it, duplicate execution problem just bubbles up. Im not sure how to ensure single execution with async data detching because `itemRenderer` causes unpredictable updates, which could happen before new data arrives or even before `this.prop.isLoading` changes and avoids new requests.

**Comment by eysi09** [comment]
I agree with @unirey, checking the index in the render function feels wrong. Is that the recommended way of doing things? An `onEndReached` callback or similar would be nice.

**Comment by blaiz** [comment]
Yes, an `onEndReached` call back would be nice. Is there an preferred way which this library to fetch more data when the user reaches the bottom of the page?

**Comment by ndford2015** [comment]
You can add an onScroll event listener that checks whether or not the bottom of the viewport is within a certain distance of the bottom of the page. Something like the following should work: 

`componentDidMount() {
    window.addEventListener('scroll', this.onScroll);
  }`

`onScroll = () => {
    // Entire page
    let d = document.documentElement;
    // Viewport height is defined differently across browsers
    let viewportHeight = window.innerHeight
    || document.documentElement.clientHeight
    || document.body.clientHeight;
    // distance of viewport bottom to top of the page
    let offset = d.scrollTop + viewportHeight;
    // height of the entire page
    let height = d.offsetHeight;
    // Distance from bottom of the page before completing some action
    let padding = 30;
    if (offset >= (height - padding)) {
     //Do something (e.g get more items)
    }
  };`

You can do something similar to check whether or not a component is at the bottom of the viewport by adding a ref to the component:

`onScroll = () => {

    //Make sure the element is still mounted
    if (this.element !== null) {
      let ele = this.element;
      let bottom = ele.getBoundingClientRect().bottom;
      let viewportHeight =  window.innerHeight
        || document.documentElement.clientHeight
        || document.body.clientHeight;
      let padding = 30;
      if (bottom <= (viewportHeight - padding) && this.state.numLoads < 2) {
        //Do something (e.g get more items)
    }
  };`

`render() {
    return (
      <div  ref={(elem) => this.element = elem}>
          <h3>Header Text</h3>
      </div>
    )
  }
}`

**Comment by Bamieh** [comment]
@ndford2015 just a hint, try to use the `passive` option to get a nice performance boost on the code above.

```
export default function isPassiveSupported() {
    if(typeof window === 'undefined') return false;

    let supportsPassiveOption = false;
    try {
      const opts = Object.defineProperty({}, 'passive', {
        get() {
          supportsPassiveOption = true;
        }
      });
      window.addEventListener('test', null, opts);
    } catch (e) {}
    return supportsPassiveOption;
};
```

Then inside a react component:
```
componentDidMount() {
   this.usePassive = isPassiveSupported()? { passive: true } : false;
   window.addEventListener('scroll', this.onScroll, this.usePassive);
}
```
